# Generated by Django 5.2.8 on 2025-11-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ajustestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradastockitem',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='requiere_caducidad',
            field=models.BooleanField(default=False),
        ),
    ]
