# Generated by Django 5.2.8 on 2025-12-02 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cliente_saldo_actual_movimientocliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_efectivo_sistema', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tarjeta_sistema', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_credito_sistema', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dinero_en_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
