# Generated by Django 5.2.8 on 2025-12-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cortecaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortecaja',
            name='tipo',
            field=models.CharField(choices=[('CORTE', 'Corte de Caja'), ('ARQUEO', 'Arqueo de Caja')], default='CORTE', max_length=10),
        ),
    ]
