# Generated by Django 5.2.8 on 2025-12-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cortecaja_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='permite_descuento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_utilidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='tasa_ieps',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='tasa_iva',
            field=models.DecimalField(decimal_places=2, default=0.16, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_venta',
            field=models.CharField(choices=[('UNIDAD', 'Por Unidad/Pieza'), ('GRANEL', 'A Granel (Kg/Lt)'), ('CAJA', 'Por Caja/Paquete')], default='UNIDAD', max_length=10),
        ),
    ]
