# Generated by Django 5.2.8 on 2025-12-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_producto_permite_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
