# Generated by Django 5.2.8 on 2025-12-12 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_producto_fecha_caducidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entradastock',
            name='factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entradastock',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('TRANSFERENCIA', 'Transferencia')], default='COMPRA', max_length=20),
        ),
        migrations.AddField(
            model_name='entradastockitem',
            name='precio_venta_sugerido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='entradastockitem',
            name='tasa_ieps',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='entradastockitem',
            name='tasa_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='entradastock',
            name='sucursal_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_transferencia', to='api.sucursal'),
        ),
    ]
