# Generated by Django 5.2.8 on 2025-12-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sucursal_entradastock_factura_entradastock_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortecaja',
            name='detalles',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
