# Generated by Django 5.2.8 on 2025-12-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_cortecaja_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clave_sat_producto',
            field=models.CharField(blank=True, default='01010101', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='clave_sat_unidad',
            field=models.CharField(blank=True, default='H87', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='objeto_impuesto',
            field=models.CharField(blank=True, default='02', max_length=20, null=True),
        ),
    ]
