# Generated by Django 5.2.10 on 2026-01-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_cliente_limite_credito_ticketsuspendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradastockitem',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
