# Generated by Django 5.2.10 on 2026-01-13 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_ventapago_tipo_cambio_alter_ventapago_metodo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='Mi Tienda', max_length=255)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje_ticket', models.TextField(blank=True, default='¡Gracias por su compra!', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion_fiscal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='saldo_actual',
        ),
        migrations.RemoveField(
            model_name='movimientocliente',
            name='venta',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cp_fiscal',
            field=models.CharField(blank=True, help_text='Código Postal Fiscal', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='credito_disponible',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dias_credito',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regimen_fiscal',
            field=models.CharField(blank=True, help_text='Clave del régimen fiscal (ej. 601)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uso_cfdi',
            field=models.CharField(blank=True, help_text='Uso del CFDI (ej. G03)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movimientocliente',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ventapago',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
