# Generated by Django 5.2.8 on 2025-11-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_4', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_5', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_6', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
