# Generated by Django 5.2.9 on 2025-12-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_producto_clave_sat_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_paquete',
            field=models.BooleanField(default=False, help_text='Indica si este producto es un paquete/kit compuesto de otros productos'),
        ),
        migrations.CreateModel(
            name='ProductoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad de este componente incluida en el paquete', max_digits=10)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_donde_aparece', to='api.producto')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='api.producto')),
            ],
            options={
                'unique_together': {('paquete', 'componente')},
            },
        ),
    ]
