# Generated by Django 5.2.10 on 2026-02-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_perfilusuario_transferencia_transferenciaitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='encabezado_personalizado',
            field=models.TextField(blank=True, help_text='Texto opcional para reemplazar o añadir al encabezado estándar', null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='mostrar_encabezado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='mostrar_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='mostrar_pie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='ticket_font_size',
            field=models.IntegerField(default=12, help_text='Tamaño de fuente para la impresión (px)'),
        ),
    ]
