# Generated by Django 5.2.10 on 2026-02-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_configuracion_encabezado_personalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to='avatars/'),
        ),
    ]
