# Generated by Django 5.2.10 on 2026-02-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_perfilusuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ganancia_fija',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto fijo de ganancia si aplica', max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_ganancia',
            field=models.CharField(choices=[('porcentaje', 'Porcentaje (%)'), ('fijo', 'Monto Fijo ($)')], default='porcentaje', max_length=15),
        ),
    ]
