# Generated by Django 5.2.10 on 2026-03-24 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_producto_ganancia_fija_producto_tipo_ganancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustestock',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes', to='api.sucursal'),
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortes', to='api.sucursal'),
        ),
        migrations.AddField(
            model_name='entradastock',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='api.sucursal'),
        ),
        migrations.AddField(
            model_name='retirocaja',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiros', to='api.sucursal'),
        ),
        migrations.AddField(
            model_name='venta',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='api.sucursal'),
        ),
    ]
